# ============================================================
# ARREST GAME
# File : crime/sword.sk
#
# 剣を手に持った場合に逮捕
#
# ============================================================


# ============================================================
# 手に持っているアイテムが変わった
# ============================================================

on held item change:

    # ========================================================
    # 剣か判定
    # ========================================================

    if event-item is wooden sword:
        arrest_crime(player, "sword")
        stop

    if event-item is stone sword:
        arrest_crime(player, "sword")
        stop

    if event-item is iron sword:
        arrest_crime(player, "sword")
        stop

    if event-item is copper sword:
        arrest_crime(player, "sword")
        stop

    if event-item is golden sword:
        arrest_crime(player, "sword")
        stop

    if event-item is diamond sword:
        arrest_crime(player, "sword")
        stop

    if event-item is netherite sword:
        arrest_crime(player, "sword")
        stop
